### ISSUE TITLE
css分离的问题

### ISSUE THREAD

**Issue by zhiqinyigu** [k55k32/cms-front#16]
我`npm install`以后还是启动不了。
https://diamondfsd.com  也是这个项目部署的吗？你怎么做到将css分离到`styles.css`的?

**Comment by diamondfsd** [comment]
是的，不过这个只是前端的部分，通过 npm run dev 就可以启动，css是webpack的插件进行分离的，默认就是会分离。

**Comment by zhiqinyigu** [comment]
`npm run dev`以后提示`babel-node`不是内部命令，我`install`了`babel-node`报错就没有继续试了。据我所知`nuxt`并不是完整支持`webpack`的，所以用不了`extract-text-webpack-plugin`。而且我这里默认也不能分离`css`，因为我是个例吗。。。
